### ISSUE TITLE
After setting status and Changing Held Items, changing Pokes causes the new status to persist

### ISSUE THREAD

**Issue by UnopenedClosure** [May8th1995/May8th1995#7]
1. Change a Pokemon's status to any status other than Healthy (this was tested with Poisoned and Burned)
2. Change the Pokemon's held item
3. Switch to a different Pokemon on the same side. This is observed to give the new Pokemon the same status which was set in step 1.

Even after setting the new Pokemon's status back to Healthy, future Pokemon switches also keep the status which was set in step 1

**Comment by May8th1995** [comment]
Fixed by https://github.com/May8th1995/May8th1995/commit/0a530a6b8bfee343432a04cb74628817d782fe66
